// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: extremo/msg/db/v1/enum.proto

package db

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ArtifactEnum with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ArtifactEnum) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ArtifactEnum with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ArtifactEnumMultiError, or
// nil if none found.
func (m *ArtifactEnum) ValidateAll() error {
	return m.validate(true)
}

func (m *ArtifactEnum) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ArtifactEnumMultiError(errors)
	}

	return nil
}

// ArtifactEnumMultiError is an error wrapping multiple validation errors
// returned by ArtifactEnum.ValidateAll() if the designated constraints aren't met.
type ArtifactEnumMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ArtifactEnumMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ArtifactEnumMultiError) AllErrors() []error { return m }

// ArtifactEnumValidationError is the validation error returned by
// ArtifactEnum.Validate if the designated constraints aren't met.
type ArtifactEnumValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ArtifactEnumValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ArtifactEnumValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ArtifactEnumValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ArtifactEnumValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ArtifactEnumValidationError) ErrorName() string { return "ArtifactEnumValidationError" }

// Error satisfies the builtin error interface
func (e ArtifactEnumValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sArtifactEnum.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ArtifactEnumValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ArtifactEnumValidationError{}

// Validate checks the field values on ArtifactImageEnum with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ArtifactImageEnum) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ArtifactImageEnum with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ArtifactImageEnumMultiError, or nil if none found.
func (m *ArtifactImageEnum) ValidateAll() error {
	return m.validate(true)
}

func (m *ArtifactImageEnum) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ArtifactImageEnumMultiError(errors)
	}

	return nil
}

// ArtifactImageEnumMultiError is an error wrapping multiple validation errors
// returned by ArtifactImageEnum.ValidateAll() if the designated constraints
// aren't met.
type ArtifactImageEnumMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ArtifactImageEnumMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ArtifactImageEnumMultiError) AllErrors() []error { return m }

// ArtifactImageEnumValidationError is the validation error returned by
// ArtifactImageEnum.Validate if the designated constraints aren't met.
type ArtifactImageEnumValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ArtifactImageEnumValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ArtifactImageEnumValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ArtifactImageEnumValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ArtifactImageEnumValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ArtifactImageEnumValidationError) ErrorName() string {
	return "ArtifactImageEnumValidationError"
}

// Error satisfies the builtin error interface
func (e ArtifactImageEnumValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sArtifactImageEnum.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ArtifactImageEnumValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ArtifactImageEnumValidationError{}
