//
// README: https://cloud.google.com/apis/design/standard_methods
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: extremo/api/auth/accounts/v1/account_service.proto

package accounts

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountService_Register_FullMethodName          = "/extremo.api.auth.accounts.v1.AccountService/Register"
	AccountService_Unregister_FullMethodName        = "/extremo.api.auth.accounts.v1.AccountService/Unregister"
	AccountService_GetAccountByToken_FullMethodName = "/extremo.api.auth.accounts.v1.AccountService/GetAccountByToken"
	AccountService_Login_FullMethodName             = "/extremo.api.auth.accounts.v1.AccountService/Login"
	AccountService_Logout_FullMethodName            = "/extremo.api.auth.accounts.v1.AccountService/Logout"
)

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// README: https://cloud.google.com/apis/design/standard_methods
//
// Service for reading from and writing to existing Accounts.
type AccountServiceClient interface {
	// Register registers a user as company role
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Unregister quit(cancel, unsubscribe) the membership
	Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ConfirmEmail confirms a email for it is validated or not.
	//
	//	rpc ConfirmEmail(ConfirmEmailRequest) returns (google.protobuf.Empty) {
	//	  option (google.api.http) = {
	//	    get: "/api/auth/v1/accounts/confirm/email"
	//	  };
	//	}
	//
	// // EmailExists returns a boolean. It is confirmed value that a users.email exists or not.
	//
	//	rpc EmailExists(EmailExistsRequest) returns (google.protobuf.BoolValue) {
	//	  option (google.api.http) = {
	//	    get: "/api/auth/v1/accounts/exists/email"
	//	  };
	//	}
	//
	// // AccountExists returns a boolean instead which confirms a account is alive. This ops similar login.
	//
	//	rpc AccountExists(AccountExistsRequest) returns (google.protobuf.BoolValue) {
	//	  option (google.api.http) = {
	//	    get: "/api/auth/v1/accounts/exists/account"
	//	  };
	//	}
	//
	// GetAccountByToken gets account by token
	GetAccountByToken(ctx context.Context, in *GetAccountByTokenRequest, opts ...grpc.CallOption) (*GetAccountByTokenResponse, error)
	// // Cookie returns AccountToken without token
	//
	//	rpc Cookie(CookieRequest) returns (extremo.msg.api.v1.AccountToken) {
	//	  option (google.api.http) = {
	//	    get: "/api/auth/v1/accounts/cookie"
	//	  };
	//	}
	//
	// Login returns a account
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Logout just notify to api server
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AccountService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_Unregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccountByToken(ctx context.Context, in *GetAccountByTokenRequest, opts ...grpc.CallOption) (*GetAccountByTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountByTokenResponse)
	err := c.cc.Invoke(ctx, AccountService_GetAccountByToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AccountService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
// All implementations must embed UnimplementedAccountServiceServer
// for forward compatibility.
//
// README: https://cloud.google.com/apis/design/standard_methods
//
// Service for reading from and writing to existing Accounts.
type AccountServiceServer interface {
	// Register registers a user as company role
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Unregister quit(cancel, unsubscribe) the membership
	Unregister(context.Context, *UnregisterRequest) (*emptypb.Empty, error)
	// ConfirmEmail confirms a email for it is validated or not.
	//
	//	rpc ConfirmEmail(ConfirmEmailRequest) returns (google.protobuf.Empty) {
	//	  option (google.api.http) = {
	//	    get: "/api/auth/v1/accounts/confirm/email"
	//	  };
	//	}
	//
	// // EmailExists returns a boolean. It is confirmed value that a users.email exists or not.
	//
	//	rpc EmailExists(EmailExistsRequest) returns (google.protobuf.BoolValue) {
	//	  option (google.api.http) = {
	//	    get: "/api/auth/v1/accounts/exists/email"
	//	  };
	//	}
	//
	// // AccountExists returns a boolean instead which confirms a account is alive. This ops similar login.
	//
	//	rpc AccountExists(AccountExistsRequest) returns (google.protobuf.BoolValue) {
	//	  option (google.api.http) = {
	//	    get: "/api/auth/v1/accounts/exists/account"
	//	  };
	//	}
	//
	// GetAccountByToken gets account by token
	GetAccountByToken(context.Context, *GetAccountByTokenRequest) (*GetAccountByTokenResponse, error)
	// // Cookie returns AccountToken without token
	//
	//	rpc Cookie(CookieRequest) returns (extremo.msg.api.v1.AccountToken) {
	//	  option (google.api.http) = {
	//	    get: "/api/auth/v1/accounts/cookie"
	//	  };
	//	}
	//
	// Login returns a account
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Logout just notify to api server
	Logout(context.Context, *LogoutRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountServiceServer struct{}

func (UnimplementedAccountServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAccountServiceServer) Unregister(context.Context, *UnregisterRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unregister not implemented")
}
func (UnimplementedAccountServiceServer) GetAccountByToken(context.Context, *GetAccountByTokenRequest) (*GetAccountByTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountByToken not implemented")
}
func (UnimplementedAccountServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAccountServiceServer) Logout(context.Context, *LogoutRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}
func (UnimplementedAccountServiceServer) testEmbeddedByValue()                        {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	// If the following call pancis, it indicates UnimplementedAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_Unregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Unregister(ctx, req.(*UnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAccountByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountByTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccountByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetAccountByToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccountByToken(ctx, req.(*GetAccountByTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "extremo.api.auth.accounts.v1.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AccountService_Register_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _AccountService_Unregister_Handler,
		},
		{
			MethodName: "GetAccountByToken",
			Handler:    _AccountService_GetAccountByToken_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AccountService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AccountService_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "extremo/api/auth/accounts/v1/account_service.proto",
}
